### ISSUE TITLE
vAlign for Row contains wrong enums

### ISSUE THREAD

**Issue by pratomchaip** [idibidiart/react-native-responsive-grid#11]
Using ```<Row vAlign="bottom">...</Row>``` displays a warning: 

> Warning: Failed prop type: Invalid prop `vAlign` of value `bottom` supplied to `Row`, expected one of ["stretch","middle","right","left"].

On closer inspection of the `/src/component/Row.js` code, it has:
`62:   vAlign: PropTypes.oneOf(['stretch', 'middle', 'right', 'left']),`

which doesn't follow the Docs:
> vAlign may also be supplied as prop to Row to align the columns within it in the vertical direction. Possible values are: top, middle, bottom, baseline and stretch. Default is top.

Fix, update enum list to:
`62:   vAlign: PropTypes.oneOf(['top', 'middle', 'bottom', 'baseline', 'stretch']),`

**Comment by idibidiart** [comment]
Thank you @pratomchaip 

This has been fixed in 0.34.05, and has been published to npm
