### ISSUE TITLE
Question not an issue

### ISSUE THREAD

**Issue by smooJitter** [idibidiart/react-native-responsive-grid#16]
I'm curious, have you compared this library to other responsive-grid libraries, particularly "react-native-easy-grid"?   It appears this system is much more comprehensive (according the api) but I am wondering to what end. Can you share a few notes on how they compare?  Can you explain your motivation for writing this packaged instead of going with "easy-grid"?

**Comment by idibidiart** [comment]
Really not a question for this thread. Goal is to build display:grid support in userland. It’s half way there with the Pinterest JS based layout. 

Closing and feel free to reopen if the structure I suggested doesn’t work for you. It should!

**Comment by smooJitter** [comment]
It does and I think it’s a amazing.  There’s seems to be so much more power with this version.
