### ISSUE TITLE
Column heights and row widths

### ISSUE THREAD

**Issue by smooJitter** [idibidiart/react-native-responsive-grid#17]
Hello,  I’m having setting the width of rows and the height of columns.  I’d like for all columns to stretch to match the height of their containing row and for all rows to match the width of their containing column.  It appears the height of a column is determined by content. I like to have the min-height set to match the height of its parent row

**Comment by idibidiart** [comment]
Use the stretch setting. See the docs. Row can stretch a column within it vertically and columns can stretch rows within them horizontally. This is just flexbox alignItems behavior. And you can set anything you want in style as far as minHeight etc.
