### ISSUE TITLE
Unable to resolve module `prop-types`

### ISSUE THREAD

**Issue by shukerullah** [idibidiart/react-native-responsive-grid#3]
Why are you using 'prop-types' instead of React.PropTypes? 

```
"dependencies": {
	"react": "16.0.0-alpha.6",
	"react-native": "0.44.0",
	"react-native-responsive-grid": "^0.21.0"
}
```

**Comment by idibidiart** [comment]
See migration guide:

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

PropTypes is being taken out of React to reduce size of React core.
