### ISSUE TITLE
Is ImageBackground supported?

### ISSUE THREAD

**Issue by wilmoore** [idibidiart/react-native-responsive-grid#38]
I have a background image that has a textual logo on it. When I set the image to stretch, the text gets stretched and looks terrible. My thinking is to export the background at several aspect ratios and have those loaded dynamically. I see that `<Image>` is supported. Is `<ImageBackground>` also supported?

**Comment by idibidiart** [comment]
Yes, see https://github.com/idibidiart/react-native-responsive-grid/blob/1a9fdd10bf871fb8fb5314783ebd8c88650b27ed/UniversalPinterestLayout.md
