### ISSUE TITLE
helpers.js uses module.exports while Column.js uses imports

### ISSUE THREAD

**Issue by skylinezum** [idibidiart/react-native-responsive-grid#40]
Mixing module.exports and import instead of require causes many problems. Better to just used a named export for each function

```
export const <function name>
```

**Comment by idibidiart** [comment]
Hi,

Please feel free to submit a pull request, but I’ve not been a maintainer on this  project for a while now. @peacechen Maybe you’d care to look into it , too?

Thank u.

**Comment by skylinezum** [comment]
Hi,

I made a PR already -> [PR](https://github.com/idibidiart/react-native-responsive-grid/pull/41)

**Comment by idibidiart** [comment]
Great. I have no way to test it unless I setup an RN environment again. Will wait first on @peacechen to see if he can test and merge. 

Thanks again. Much appreciated.

**Comment by peacechen** [comment]
Thanks @skylinezum for the PR.   Tested it and works great👍

**Comment by peacechen** [comment]
@idibidiart Would you publish a new version on npm?  It's been a while.

**Comment by innerop** [comment]
@peacechen sure, I'll clone and publish later today. Will ping here. Thanks!!

**Comment by shiundu** [comment]
Has this been fixed in the current version?

```
./node_modules/react-native-responsive-grid/src/components/Column.js
Attempted import error: 'getOffset' is not exported from '../lib/helpers'.
```
I am having issues with export/import

**Comment by idibidiart** [comment]
No I was supposed to publish it a while ago,

Problem is I no longer have the RN environment to test the latest commit but I’ll do an npm push (tonight) based on @peacechen ’s test.

**Comment by idibidiart** [comment]
Sorry for the terribly long delay.

**Comment by idibidiart** [comment]
Finally, published

Sorry about that. Closing now.

$ npm publish
npm notice
npm notice 📦  react-native-responsive-grid@0.41.993
npm notice === Tarball Contents ===
npm notice 7.5kB  src/components/Column.js
npm notice 1.9kB  src/components/Grid.js
npm notice 4.6kB  src/lib/helpers.js
npm notice 224B   src/index.js
npm notice 6.1kB  src/components/Row.js
npm notice 4.2kB  src/lib/ScreenInfo.js
npm notice 948B   package.json
npm notice 5.7kB  CHANGELOG.md
npm notice 5.1kB  CONTRIBUTING.md
npm notice 3.7kB  DesignPrinciples.md
npm notice 13.4kB EvenMoreExamples.md
npm notice 155B   .github/ISSUE_TEMPLATE.md
npm notice 1.2kB  LICENSE.md
npm notice 33.2kB README.md
npm notice 6.9kB  UniversalPinterestLayout.md
npm notice 2.9kB  UniversalTiles.md
npm notice === Tarball Details ===
npm notice name:          react-native-responsive-grid
npm notice version:       0.41.993
npm notice package size:  25.2 kB
npm notice unpacked size: 97.8 kB
npm notice shasum:        5d84e4340e67c5888b38939cc3496ae5942dae13
npm notice integrity:     sha512-vyFXRArmYoXZm[...]YS8oPZDlhFyGw==
npm notice total files:   16
npm notice
+ react-native-responsive-grid@0.41.993
