### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by srameshr** [idibidiart/react-native-responsive-grid#7]
Hi, the docs look great and very informative. But is there any example of how to do a photo grid of images of varying sizes? Like an image collage?

**Comment by idibidiart** [comment]
Here is an example using the latest version of the grid:

https://www.youtube.com/watch?v=QyIRoKinyLU

See the updated Readme for source 

You'll have to write your own custom layout function if you wish to do something more fancy.

Also, masonry type transitions are not part of the design goal. 

Closing this.
