### ISSUE TITLE
crashes expo with simple example

### ISSUE THREAD

**Issue by Morriz** [idibidiart/react-native-responsive-grid#8]
I am using
```
"react": "16.0.0-alpha.12",
"react-native-responsive-grid": "^0.32.4",
```
The following just crashes my CRNA (uses expo) setup:

```
      <Row>
        <Col size={20} offset={5}>
          <Text style={styles.text}>
            asdfas
          </Text>
        </Col>
        <Col size={20} offset={5}>
          <Text style={styles.text}>
            asdfasdfs
          </Text>
        </Col>
        <Col size={20} offset={5}>
          <Text style={styles.text}>
           asdfasdfasdfa
          </Text>
        </Col>
        <Col size={20} offset={5}>
          <Text style={styles.text}>
            adsfasdfasdfasd
          </Text>
        </Col>
      </Row>
```

Any idea? I am sorry but I am not able to supply much more info :|

**Comment by idibidiart** [comment]
Hi,

I haven't tested it with CRNA but it should not matter. 

You're doing nothing wrong in the above and I have no idea why it crashes for you but not for others. 

See if it still crashes with v0.34.x and feel free to re-open with a bit more info (iOS or Android? which device are you simulating or testing on actual hardware?)

Thanks
