### ISSUE TITLE
Overlay?

### ISSUE THREAD

**Issue by Jonovono** [idibidiart/react-native-responsive-grid#9]
This looks like an awesome library! 

One thing I am wondering is how I would place an overlay over a certain row. Position absolute feels weird because I want it as an overlay for that specific row view.

Here is a simple example:

```
      <Row size={50} style={{backgroundColor: 'green'}}>
        <WebView source={{uri: "https://google.com"}} />
      </Row>
```

Say I want something on top of the webview, how would you go about it?

Thanks!

**Comment by idibidiart** [comment]
This is not a requirement that I've ran into yet, but you can modify the source to omit ```position: 'relative'``` from Row.js so you can set that Row to position absolute by itself. I would not recommend that. I would maybe wrap the Row in a View and set that as position absolute.
